# yaml-language-server: $schema=../../vendor/symfony/dependency-injection/Loader/schema/services.schema.json
parameters:
    env(S3_KEY): key
    env(S3_SECRET): secret
    env(S3_ENDPOINT): null
    env(S3_REGION): 'eu-west-3'
    env(S3_BUCKET): 'cvvfcm'

flysystem:
    storages:
        default.storage:
            adapter: 'asyncaws'
            options:
                client: 'AsyncAws\S3\S3Client'
                bucket: '%env(S3_BUCKET)%'
                prefix: ''


services:
    # On définit le nouveau client AsyncAWS
    AsyncAws\S3\S3Client:
        class: AsyncAws\S3\S3Client
        arguments:
            -
                region: '%env(S3_REGION)%'
                endpoint: '%env(S3_ENDPOINT)%'
                accessKeyId: '%env(S3_KEY)%'
                accessKeySecret: '%env(S3_SECRET)%'
                pathStyleEndpoint: true
