parameters:
    env(MERCURE_URL): 'http://php/.well-known/mercure'
    env(MERCURE_PUBLIC_URL): '/.well-known/mercure'
    env(MERCURE_JWT_SECRET): ''

mercure:
    hubs:
        default:
            url: '%env(MERCURE_URL)%'
            public_url: '%env(MERCURE_PUBLIC_URL)%'
            jwt:
                secret: '%env(MERCURE_JWT_SECRET)%'
                publish: '*'
