services:
    php:
        volumes:
            - '.:/app:rw'
            - './infra/docker/php/conf.d/symfony.dev.ini:/usr/local/etc/php/conf.d/symfony.ini:ro'
        depends_on: [ database, mailer ]
        environment:
            CADDY_SERVER_EXTRA_DIRECTIVES: ${CADDY_SERVER_EXTRA_DIRECTIVES:-tls /app/infra/tls/cert.pem /app/infra/tls/key.pem}
            FRANKENPHP_WORKER_CONFIG: watch
            APP_ENV: ${APP_ENV:-dev}
            DATABASE_URL: ${DATABASE_URL:-pgsql://${POSTGRES_USER:-cvvfcm}:${POSTGRES_PASSWORD:-cvvfcm}@database:5432/${POSTGRES_DB:-cvvfcm}?serverVersion=18&charset=utf8}
        extra_hosts:
            - host.docker.internal:host-gateway
        tty: true
        command: [ "frankenphp", "run", "--config", "/etc/caddy/Caddyfile", "--watch" ]

    mailer:
        image: axllent/mailpit
        ports: [ '${MAILER_HTTP_PORT:-8025}:8025' ]
        environment:
            MP_SMTP_AUTH_ACCEPT_ANY: 1
            MP_SMTP_AUTH_ALLOW_INSECURE: 1

    database:
        image: postgres:18
        environment:
            POSTGRES_DB: ${POSTGRES_DB:-cvvfcm}
            POSTGRES_USER: ${POSTGRES_USER:-cvvfcm}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-cvvfcm}
        ports: [ '${MYSQL_PORT:-3306}:3306' ]
        volumes:
            - database_data:/var/lib/mysql

    rtsp-to-web:
        ports: [ '${RTSP_TO_WEB_PORT:-8083}:8083' ]

volumes:
    database_data:
