services:
    php:
        image: ${IMAGE_PREFIX:-ghcr.io/cvvfcm/website/}php:${IMAGE_TAG:-latest}
        depends_on: [ database, rtsp-to-web ]
        restart: unless-stopped
        build:
            target: php
            args:
                EXTERNAL_USER_ID: ${EXTERNAL_USER_ID}
        environment: &php-env
            SERVER_NAME: ${SERVER_SCHEME:-https://}${SERVER_NAME:-localhost}
            APP_SECRET: ${APP_SECRET:-!ChangeMe!}
            MAILER_DSN: ${MAILER_DSN:-smtp://mailer:1025}
            DATABASE_URL: ${DATABASE_URL:-pgsql://${POSTGRES_USER:-cvvfcm}:${POSTGRES_PASSWORD:-cvvfcm}@database:5432/${POSTGRES_DB:-cvvfcm}?serverVersion=18&charset=utf8}
            SULU_ADMIN_EMAIL: ${SULU_ADMIN_EMAIL:-"CVVFCM <contact@cvvfcm.fr>"}
            APP_ENV: ${APP_ENV:-prod}
            SYMFONY_DECRYPTION_SECRET: ${SYMFONY_DECRYPTION_SECRET:-}
            S3_KEY: ${S3_KEY:-}
            S3_SECRET: ${S3_SECRET:-}
            S3_ENDPOINT: ${S3_ENDPOINT:-}
            S3_REGION: ${S3_REGION:-eu-west-3}
            S3_BUCKET: ${S3_BUCKET:-cvvfcm}
        labels:
            - 'traefik.enable=true'
            - 'traefik.docker.network=${NETWORK_NAME:-${COMPOSE_PROJECT_NAME}_default}'
            - 'traefik.http.routers.${COMPOSE_PROJECT_NAME}.rule=Host(`${SERVER_NAME:-localhost}`)'
            - 'traefik.http.routers.${COMPOSE_PROJECT_NAME}.tls=true'
            - 'traefik.http.routers.${COMPOSE_PROJECT_NAME}.tls.certresolver=letsencrypt'
            - 'traefik.http.routers.${COMPOSE_PROJECT_NAME}.tls.domains[0].main=${SERVER_NAME:-localhost}'
        volumes:
            - caddy_data:/data
            - caddy_config:/config
            - search_indexes:/app/var/indexes
            - thumbnails:/app/public/uploads

    rtsp-to-web:
        image: ${IMAGE_PREFIX:-ghcr.io/cvvfcm/website/}rtsp-to-web:${IMAGE_TAG:-latest}
        restart: unless-stopped
        build:
            context: .infra/docker/rtsp-to-web
            target: rtsp-to-web
        environment:
            HTTP_LOGIN: '${RTSP_TO_WEB_HTTP_LOGIN:-admin}'
            HTTP_PASSWORD: '${RTSP_TO_WEB_HTTP_PASSWORD:-!ChangeMe!}'

    ml:
        image: ${IMAGE_PREFIX:-ghcr.io/cvvfcm/website/}ml:${IMAGE_TAG:-latest}
        build:
            context: ml
            target: python
            args:
                EXTERNAL_USER_ID: ${EXTERNAL_USER_ID}

    consumer:
        image: ${IMAGE_PREFIX:-ghcr.io/cvvfcm/website/}consumer:${IMAGE_TAG:-latest}
        depends_on: [ database ]
        restart: unless-stopped
        build:
            target: consumer
            args:
                EXTERNAL_USER_ID: ${EXTERNAL_USER_ID}
        environment: *php-env

    database:
        image: postgres:18
        environment:
            POSTGRES_DB: ${POSTGRES_DB:-cvvfcm}
            POSTGRES_USER: ${POSTGRES_USER:-cvvfcm}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-cvvfcm}
        volumes:
            - database_data:/var/lib/mysql

volumes:
    caddy_data:
    caddy_config:
    database_data:
    search_indexes:
    thumbnails:

networks:
    default:
        external: ${NETWORK_EXTERNAL:-false}
        name: ${NETWORK_NAME:-${COMPOSE_PROJECT_NAME}_default}
