services:
    php:
        volumes:
            - '.:/app:rw'
            - './infra/docker/php/conf.d/symfony.dev.ini:/usr/local/etc/php/conf.d/symfony.ini:ro'
        depends_on: [ database, mailer, s3 ]
        environment:
            CADDY_SERVER_EXTRA_DIRECTIVES: ${CADDY_SERVER_EXTRA_DIRECTIVES:-tls /app/infra/tls/cert.pem /app/infra/tls/key.pem}
            PHP_SERVER_CONFIG: hot_reload
            COMMON_EXTRA_CONFIG: |
                mercure {
                    anonymous
                }
            FRANKENPHP_WORKER_CONFIG: watch
            APP_ENV: ${APP_ENV:-dev}
            S3_ENDPOINT: http://s3:9090
        extra_hosts:
            - host.docker.internal:host-gateway
        tty: true
        command: [ "frankenphp", "run", "--config", "/etc/frankenphp/Caddyfile", "--watch" ]

    mailer:
        image: axllent/mailpit
        ports: [ '${MAILER_HTTP_PORT:-8025}:8025' ]
        environment:
            MP_SMTP_AUTH_ACCEPT_ANY: 1
            MP_SMTP_AUTH_ALLOW_INSECURE: 1

    database:
        image: postgres:18
        environment:
            POSTGRES_DB: ${POSTGRES_DB:-cvvfcm}
            POSTGRES_USER: ${POSTGRES_USER:-cvvfcm}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-cvvfcm}
        ports: [ '${POSTGRES_PORT:-5432}:5432' ]
        volumes:
            - database_data:/var/lib/mysql

    s3:
        image: adobe/s3mock:latest
        environment:
            COM_ADOBE_TESTING_S3MOCK_STORE_INITIAL_BUCKETS: ${S3_BUCKET:-cvvfcm}
            COM_ADOBE_TESTING_S3MOCK_STORE_RETAIN_FILES_ON_EXIT: true
        volumes:
            - s3_data:/s3mockroot

    ml:
        environment:
            - DISPLAY
        volumes:
            - '.:/app:rw'
            - './data/weather/ml:/app/data/weather/ml:rw'
            - '/tmp/.X11-unix:/tmp/.X11-unix'

    consumer:
        volumes:
            - '.:/app:rw'
        depends_on: [ database, mailer, s3, php ]
        environment:
            APP_ENV: ${APP_ENV:-dev}
        tty: true

    rtsp-to-web:
        ports:
            - '${RTSP_TO_WEB_PORT:-8083}:8083'
volumes:
    database_data:
    s3_data:
