services:
    php:
        volumes:
            - '.:/app:rw'
            - './infra/docker/php/conf.d/symfony.dev.ini:/usr/local/etc/php/conf.d/symfony.ini:ro'
        depends_on: [ database, mailer, localstack ]
        environment:
            CADDY_SERVER_EXTRA_DIRECTIVES: ${CADDY_SERVER_EXTRA_DIRECTIVES:-tls /app/infra/tls/cert.pem /app/infra/tls/key.pem}
            FRANKENPHP_WORKER_CONFIG: watch
            APP_ENV: ${APP_ENV:-dev}
            S3_ENDPOINT: http://localstack:4566
        extra_hosts:
            - host.docker.internal:host-gateway
        tty: true
        command: [ "frankenphp", "run", "--config", "/etc/caddy/Caddyfile", "--watch" ]

    mailer:
        image: axllent/mailpit
        ports: [ '${MAILER_HTTP_PORT:-8025}:8025' ]
        environment:
            MP_SMTP_AUTH_ACCEPT_ANY: 1
            MP_SMTP_AUTH_ALLOW_INSECURE: 1

    database:
        image: postgres:18
        environment:
            POSTGRES_DB: ${POSTGRES_DB:-cvvfcm}
            POSTGRES_USER: ${POSTGRES_USER:-cvvfcm}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-cvvfcm}
        ports: [ '${POSTGRES_PORT:-5432}:5432' ]
        volumes:
            - database_data:/var/lib/mysql

    localstack:
        image: localstack/localstack:latest
        environment:
            S3_BUCKET: ${S3_BUCKET:-cvvfcm}
        volumes:
            - localstack_data:/var/lib/localstack
            - ./infra/docker/localstack/create-bucket.sh:/etc/localstack/init/ready.d/create-bucket.sh:ro


volumes:
    database_data:
    localstack_data:
