apiVersion: v1
kind: Service
metadata:
  name: {{ include "cvvfcm.fullname" . }}-web
  labels:
    {{- include "cvvfcm.labels" . | nindent 4 }}
    app.kubernetes.io/component: web
spec:
  type: ClusterIP
  selector:
    {{- include "cvvfcm.web.selectorLabels" . | nindent 4 }}
  ports:
    - name: http
      port: 80
      targetPort: http
      protocol: TCP
